name: CA Clone Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  ca-clone-test:
    name: CA clone
    needs: build
    uses: ./.github/workflows/ca-clone-test.yml

  ca-clone-hsm-test:
    name: CA clone with HSM
    needs: build
    uses: ./.github/workflows/ca-clone-hsm-test.yml

  ca-clone-secure-ds-test:
    name: CA clone with secure DS
    needs: build
    uses: ./.github/workflows/ca-clone-secure-ds-test.yml

  ca-clone-shared-ds-test:
    name: CA clone with shared DS
    needs: build
    uses: ./.github/workflows/ca-clone-shared-ds-test.yml

  ca-clone-replicated-ds-test:
    name: CA clone with replicated DS
    needs: build
    uses: ./.github/workflows/ca-clone-replicated-ds-test.yml

  ca-clone-ssnv1-test:
    name: CA clone with SSNv1
    needs: build
    uses: ./.github/workflows/ca-clone-ssnv1-test.yml

  ca-clone-ssnv2-test:
    name: CA clone with SSNv2
    needs: build
    uses: ./.github/workflows/ca-clone-ssnv2-test.yml

  ca-clone-mldsa-test:
    name: CA clone with ML-DSA
    needs: build
    uses: ./.github/workflows/ca-clone-mldsa-test.yml
