name: EST on separate instance with provided certificates

on: workflow_call

env:
  DB_IMAGE: ${{ vars.DB_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  # docs/installation/ca/Installing_CA.md
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve PKI images
        uses: actions/cache@v4
        with:
          key: pki-images-${{ github.sha }}
          path: pki-images.tar

      - name: Load PKI images
        run: docker load --input pki-images.tar

      - name: Create network
        run: docker network create example

      - name: Set up CA DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DB_IMAGE }} \
              --hostname=cads.example.com \
              --password=Secret.123 \
              --network=example \
              --network-alias=cads.example.com \
              cads

      - name: Set up CA container
        run: |
          tests/bin/runner-init.sh \
          --hostname=ca.example.com \
          --network=example \
          --network-alias=ca.example.com \
          ca

      - name: Install CA
        run: |
          docker exec ca pkispawn \
              -f /usr/share/pki/server/examples/installation/ca.cfg \
              -s CA \
              -D pki_ds_url=ldap://cads.example.com:3389 \
              -D pki_security_domain_setup=False \
              -v

      - name: Initialize PKI client
        run: |
          docker exec ca pki-server cert-export ca_signing --cert-file $SHARED/ca_signing.crt

          docker exec ca pki nss-cert-import \
              --cert $SHARED/ca_signing.crt \
              --trust CT,C,C \
              ca_signing

          docker exec ca pki pkcs12-import \
              --pkcs12 /root/.dogtag/pki-tomcat/ca_admin_cert.p12 \
              --password Secret.123

          docker exec ca pki info

      - name: Set up EST DS container
        run: |
          tests/bin/ds-create.sh \
              --image=${{ env.DB_IMAGE }} \
              --hostname=estds.example.com \
              --password=Secret.123 \
              --network=example \
              --network-alias=estds.example.com \
              estds

      - name: Set up EST container
        run: |
          tests/bin/runner-init.sh \
          --hostname=est.example.com \
          --network=example \
          --network-alias=est.example.com \
          est

          # get Fedora version
          FEDORA_VERSION=$(docker exec est sed -n 's/^VERSION_ID=//p' /etc/os-release)
          echo "FEDORA_VERSION=$FEDORA_VERSION" >> $GITHUB_ENV

      - name: Set up EST user DB
        run: |
          docker exec -i est ldapadd -x -H ldap://estds.example.com:3389 \
              -D "cn=Directory Manager"  -w Secret.123 \
              -f /usr/share/pki/est/conf/realm/ds/create.ldif

      - name: Install EST (step 1)
        run: |
          docker exec est pkispawn \
              -f /usr/share/pki/server/examples/installation/est-standalone.cfg \
              -s EST \
              -D est_realm_url=ldap://estds.example.com:3389 \
              -D pki_ca_uri=https://ca.example.com:8443 \
              -D est_ca_user_password= \
              -D pki_cert_chain_nickname=ca_signing \
              -D pki_subsystem_csr_path=${SHARED}/subsystem.csr \
              -D pki_sslserver_csr_path=${SHARED}/sslserver.csr \
              -D pki_cert_chain_path=${SHARED}/ca_signing.crt \
              -D pki_external_step_two=False \
              -v

      - name: Issue subsystem cert
        run: |
          docker exec ca openssl req -text -noout -in ${SHARED}/subsystem.csr
          docker exec ca pki \
              -n caadmin \
              ca-cert-issue \
              --profile caSubsystemCert \
              --csr-file ${SHARED}/subsystem.csr \
              --output-file ${SHARED}/subsystem.crt
          docker exec ca openssl x509 -text -noout -in ${SHARED}/subsystem.crt

      - name: Issue SSL server cert
        run: |
          docker exec ca openssl req -text -noout -in ${SHARED}/sslserver.csr
          docker exec ca pki \
              -n caadmin \
              ca-cert-issue \
              --profile caServerCert \
              --csr-file ${SHARED}/sslserver.csr \
              --output-file ${SHARED}/sslserver.crt
          docker exec ca openssl x509 -text -noout -in ${SHARED}/sslserver.crt

      - name: Stop CA
        run: |
          docker exec ca pki-server stop --wait

      - name: Install EST (step 2)
        run: |
          docker exec est pkispawn \
              -f /usr/share/pki/server/examples/installation/est-standalone.cfg \
              -s EST \
              -D est_realm_url=ldap://estds.example.com:3389 \
              -D pki_ca_uri=https://ca.example.com:8443 \
              -D est_ca_user_password= \
              -D pki_cert_chain_nickname=ca_signing \
              -D pki_subsystem_csr_path=${SHARED}/subsystem.csr \
              -D pki_subsystem_cert_path=${SHARED}/subsystem.crt \
              -D pki_sslserver_csr_path=${SHARED}/sslserver.csr \
              -D pki_sslserver_cert_path=${SHARED}/sslserver.crt \
              -D pki_cert_chain_path=${SHARED}/ca_signing.crt \
              -D pki_external_step_two=True \
              -v

      - name: Check EST server base dir after installation
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/lib/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          # TODO: review permissions
          cat > expected << EOF
          lrwxrwxrwx pkiuser pkiuser alias -> /var/lib/pki/pki-tomcat/conf/alias
          lrwxrwxrwx pkiuser pkiuser bin -> /usr/share/tomcat/bin
          drwxrwx--- pkiuser pkiuser common
          lrwxrwxrwx pkiuser pkiuser conf -> /etc/pki/pki-tomcat
          drwxrwx--- pkiuser pkiuser est
          lrwxrwxrwx pkiuser pkiuser lib -> /usr/share/pki/server/lib
          lrwxrwxrwx pkiuser pkiuser logs -> /var/log/pki/pki-tomcat
          drwxrwx--- pkiuser pkiuser temp
          drwxr-xr-x pkiuser pkiuser webapps
          drwxrwx--- pkiuser pkiuser work
          EOF

          diff expected output

      - name: Check EST server conf dir after installation
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /etc/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser Catalina
          drwxrwx--- pkiuser pkiuser alias
          -rw-r--r-- pkiuser pkiuser catalina.policy
          lrwxrwxrwx pkiuser pkiuser catalina.properties -> /usr/share/pki/server/conf/catalina.properties
          drwxrwx--- pkiuser pkiuser certs
          lrwxrwxrwx pkiuser pkiuser context.xml -> /etc/tomcat/context.xml
          drwxrwx--- pkiuser pkiuser est
          lrwxrwxrwx pkiuser pkiuser logging.properties -> /usr/share/pki/server/conf/logging.properties
          -rw-rw---- pkiuser pkiuser password.conf
          -rw-rw---- pkiuser pkiuser server.xml
          -rw-rw---- pkiuser pkiuser serverCertNick.conf
          -rw-rw---- pkiuser pkiuser tomcat.conf
          lrwxrwxrwx pkiuser pkiuser web.xml -> /etc/tomcat/web.xml
          EOF

          diff expected output

      - name: Check EST server logs dir after installation
        if: ${{ fromJSON(env.FEDORA_VERSION) < 43 }}
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/log/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          DATE=$(date +'%Y-%m-%d')

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser backup
          drwxrwx--- pkiuser pkiuser est
          -rw-r--r-- pkiuser pkiuser localhost.$DATE.log
          -rw-r--r-- pkiuser pkiuser localhost_access_log.$DATE.txt
          drwxr-xr-x pkiuser pkiuser pki
          EOF

          diff expected output

      - name: Check EST server logs dir after installation
        if: ${{ fromJSON(env.FEDORA_VERSION) >= 43 }}
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/log/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          DATE=$(date +'%Y-%m-%d')

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser backup
          drwxrwx--- pkiuser pkiuser est
          -rw-r--r-- pkiuser pkiuser localhost_access_log.$DATE.txt
          EOF

          diff expected output

      - name: Check EST conf dir
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /etc/pki/pki-tomcat/est \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          # TODO: review permissions
          cat > expected << EOF
          -rw-rw-r-- pkiuser pkiuser CS.cfg
          -rw-rw---- pkiuser pkiuser authorizer.conf
          -rw-rw---- pkiuser pkiuser backend.conf
          -rw-rw-r-- pkiuser pkiuser realm.conf
          -rw-rw-r-- pkiuser pkiuser registry.cfg
          EOF

          diff expected output

      - name: Start CA
        run: |
          docker exec ca pki-server start --wait

      - name: Add EST subsystem user in CA
        run: |
          # create EST subsystem user in CA
          docker exec ca pki \
              -n caadmin \
              ca-user-add \
              --full-name "EST-est.example.com-8443" \
              --type agentType \
              --cert-file $SHARED/subsystem.crt \
              EST-est.example.com-8443

          # allow EST to create certificates
          docker exec ca pki \
              -n caadmin \
              ca-user-membership-add \
              EST-est.example.com-8443 \
              "Certificate Manager Agents"

      - name: Test CA certs
        run: |
          docker exec est curl -o cacert.p7 -k https://est.example.com:8443/.well-known/est/cacerts

          docker exec est openssl base64 -d --in cacert.p7 --out cacert.p7.der
          docker exec est openssl pkcs7 --in cacert.p7.der -inform DER -print_certs -quiet -out cacert.pem
          docker exec est openssl x509 -in cacert.pem -text -noout | tee actual
          docker exec est openssl x509 -in $SHARED/ca_signing.crt -text -noout | tee expected
          diff expected actual

      - name: Create EST user
        run: |
          docker exec -i est ldapadd -x -H ldap://estds.example.com:3389 \
              -D "cn=Directory Manager"  -w Secret.123 << EOF
          dn: uid=est-test-user,ou=people,dc=est,dc=pki,dc=example,dc=com
          objectClass: top
          objectClass: person
          objectClass: organizationalPerson
          objectClass: inetOrgPerson
          uid: est-test-user
          sn: test.example.com
          cn: test.example.com
          userPassword: Secret.123
          EOF

      - name: Add EST user to EST Users group
        run: |
          docker exec -i est ldapmodify -x -H ldap://estds.example.com:3389 \
              -D "cn=Directory Manager"  -w Secret.123 << EOF
          dn: cn=EST Users,ou=groups,dc=est,dc=pki,dc=example,dc=com
          changetype: modify
          add: uniqueMember
          uniqueMember: uid=est-test-user,ou=People,dc=est,dc=pki,dc=example,dc=com
          EOF

      - name: Install est client
        run: |
          docker exec est dnf copr enable -y @pki/libest
          docker exec est dnf install -y libest

      - name: Enroll certificate
        run: |
          docker exec -e EST_OPENSSL_CACERT=cacert.pem est estclient -e -s est.example.com -p 8443 \
              --common-name test.example.com -o . -u est-test-user -h Secret.123

          docker exec est openssl base64 -d --in cert-0-0.pkcs7 --out cert-0-0.pkcs7.der
          docker exec est openssl pkcs7 -in cert-0-0.pkcs7.der -inform DER -print_certs -quiet -out cert.pem
          docker exec est openssl x509 -in cert.pem -subject -noout | tee actual
          echo "subject=CN=test.example.com" > expected
          diff expected actual

      - name: Remove EST
        run: |
          docker exec est pkidestroy -i pki-tomcat -s EST -v

      - name: Remove CA
        run: |
          docker exec ca pkidestroy -i pki-tomcat -s CA -v

      - name: Check EST server base dir after removal
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/lib/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          # TODO: review permissions
          cat > expected << EOF
          lrwxrwxrwx pkiuser pkiuser conf -> /etc/pki/pki-tomcat
          lrwxrwxrwx pkiuser pkiuser logs -> /var/log/pki/pki-tomcat
          EOF

          diff expected output

      - name: Check EST server conf dir after removal
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /etc/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser Catalina
          drwxrwx--- pkiuser pkiuser alias
          -rw-r--r-- pkiuser pkiuser catalina.policy
          lrwxrwxrwx pkiuser pkiuser catalina.properties -> /usr/share/pki/server/conf/catalina.properties
          drwxrwx--- pkiuser pkiuser certs
          lrwxrwxrwx pkiuser pkiuser context.xml -> /etc/tomcat/context.xml
          drwxrwx--- pkiuser pkiuser est
          lrwxrwxrwx pkiuser pkiuser logging.properties -> /usr/share/pki/server/conf/logging.properties
          -rw-rw---- pkiuser pkiuser password.conf
          -rw-rw---- pkiuser pkiuser server.xml
          -rw-rw---- pkiuser pkiuser serverCertNick.conf
          -rw-rw---- pkiuser pkiuser tomcat.conf
          lrwxrwxrwx pkiuser pkiuser web.xml -> /etc/tomcat/web.xml
          EOF

          diff expected output

      - name: Check EST server logs dir after removal
        if: ${{ fromJSON(env.FEDORA_VERSION) < 43 }}
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/log/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          DATE=$(date +'%Y-%m-%d')

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser backup
          drwxrwx--- pkiuser pkiuser est
          -rw-r--r-- pkiuser pkiuser localhost.$DATE.log
          -rw-r--r-- pkiuser pkiuser localhost_access_log.$DATE.txt
          drwxr-xr-x pkiuser pkiuser pki
          EOF

          diff expected output

      - name: Check EST server logs dir after removal
        if: ${{ fromJSON(env.FEDORA_VERSION) >= 43 }}
        run: |
          # check file types, owners, and permissions
          docker exec est ls -l /var/log/pki/pki-tomcat \
              | sed \
                  -e '/^total/d' \
                  -e 's/^\(\S*\) *\S* *\(\S*\) *\(\S*\) *\S* *\S* *\S* *\S* *\(.*\)$/\1 \2 \3 \4/' \
              | tee output

          DATE=$(date +'%Y-%m-%d')

          # TODO: review permissions
          cat > expected << EOF
          drwxrwx--- pkiuser pkiuser backup
          drwxrwx--- pkiuser pkiuser est
          -rw-r--r-- pkiuser pkiuser localhost_access_log.$DATE.txt
          EOF

          diff expected output

      - name: Check CA DS server systemd journal
        if: always()
        run: |
          docker exec cads journalctl -x --no-pager -u dirsrv@localhost.service

      - name: Check CA DS container logs
        if: always()
        run: |
          docker logs cads

      - name: Check CA PKI server systemd journal
        if: always()
        run: |
          docker exec ca journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check EST PKI server systemd journal
        if: always()
        run: |
          docker exec est journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check CA debug log
        if: always()
        run: |
          docker exec ca find /var/lib/pki/pki-tomcat/logs/ca -name "debug.*" -exec cat {} \;

      - name: Check EST debug log
        if: always()
        run: |
          docker exec est find /var/lib/pki/pki-tomcat/logs/est -name "debug.*" -exec cat {} \;
