name: IPA with Sub-CA

on: workflow_call

env:
  DB_IMAGE: ${{ vars.DB_IMAGE || 'quay.io/389ds/dirsrv' }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SHARED: /tmp/workdir/pki
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Retrieve IPA images
        uses: actions/cache@v4
        with:
          key: ipa-images-${{ github.sha }}
          path: ipa-images.tar

      - name: Load IPA images
        run: docker load --input ipa-images.tar

      - name: Create network
        run: docker network create example

      - name: Run IPA container
        run: |
          tests/bin/runner-init.sh ipa
        env:
          IMAGE: ipa-runner
          HOSTNAME: ipa.example.com

      - name: Connect IPA container to network
        run: docker network connect example ipa --alias ipa.example.com --alias ipa-ca.example.com

      - name: Create root CA
        run: |
          docker exec ipa pki \
              -d nssdb \
              nss-cert-request \
              --subject "CN=Root CA Signing Certificate" \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --csr root-ca_signing.csr
          docker exec ipa pki \
              -d nssdb \
              nss-cert-issue \
              --csr root-ca_signing.csr \
              --ext /usr/share/pki/server/certs/ca_signing.conf \
              --cert root-ca_signing.crt
          docker exec ipa pki \
              -d nssdb \
              nss-cert-import \
              --cert root-ca_signing.crt \
              --trust CT,C,C \
              root-ca_signing

      - name: Generate IPA cert request
        run: |
          docker exec ipa sysctl net.ipv6.conf.lo.disable_ipv6=0
          docker exec ipa ipa-server-install \
              -U \
              --domain example.com \
              -r EXAMPLE.COM \
              -p Secret.123 \
              -a Secret.123 \
              --no-host-dns \
              --no-ntp \
              --external-ca

      - name: Issue IPA cert
        run: |
          docker exec ipa pki \
              -d nssdb \
              nss-cert-issue \
              --issuer root-ca_signing \
              --csr /root/ipa.csr \
              --ext /usr/share/pki/server/certs/subca_signing.conf \
              --cert ipa.crt

      - name: Install IPA server with Sub-CA
        run: |
          docker exec ipa ipa-server-install \
              --external-cert-file=/ipa.crt \
              --external-cert-file=/root-ca_signing.crt \
              -p Secret.123
          echo Secret.123 | docker exec -i ipa kinit admin
          docker exec ipa ipa ping

      - name: Check Sub-CA admin
        run: |
          docker exec ipa pki client-cert-import ca_signing --ca-cert root-ca_signing.crt
          docker exec ipa pki pkcs12-import \
              --pkcs12 /root/ca-agent.p12 \
              --pkcs12-password Secret.123
          docker exec ipa pki -n ipa-ca-agent ca-user-show admin

      - name: Check lightweight CAs
        run: |
          # there should be 1 authority initially
          docker exec ipa pki -n ipa-ca-agent ca-authority-find | tee output
          echo "1" > expected
          sed -n 's/^\s*ID:\s*\(.*\)$/\1/p' output | wc -l > actual
          diff expected actual

      - name: Create lightweight CAs
        run: |
          for i in {1..20}
          do
              docker exec ipa ipa ca-add "lwca$i" \
                  --subject "cn=Lightweight CA $i" \
                  --desc "Lightweight CA $i"
          done

          # there should be 21 authorities now
          docker exec ipa pki -n ipa-ca-agent ca-authority-find | tee output
          echo "21" > expected
          sed -n 's/^\s*ID:\s*\(.*\)$/\1/p' output | wc -l > actual
          diff expected actual

      - name: Remove lightweight CAs
        run: |
          for i in {1..20}
          do
              docker exec ipa ipa ca-disable "lwca$i"
              docker exec ipa ipa ca-del "lwca$i"
          done

          # there should be 1 authority now
          docker exec ipa pki -n ipa-ca-agent ca-authority-find | tee output
          echo "1" > expected
          sed -n 's/^\s*ID:\s*\(.*\)$/\1/p' output | wc -l > actual
          diff expected actual

      - name: Remove IPA server
        run: docker exec ipa ipa-server-install --uninstall -U

      - name: Check DS server systemd journal
        if: always()
        run: |
          docker exec ipa journalctl -x --no-pager -u dirsrv@EXAMPLE-COM.service

      - name: Check DS access logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/access

      - name: Check DS error logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/errors

      - name: Check DS security logs
        if: always()
        run: |
          docker exec ipa cat /var/log/dirsrv/slapd-EXAMPLE-COM/security

      - name: Check PKI server systemd journal
        if: always()
        run: |
          docker exec ipa journalctl -x --no-pager -u pki-tomcatd@pki-tomcat.service

      - name: Check CA debug log
        if: always()
        run: |
          docker exec ipa find /var/log/pki/pki-tomcat/ca -name "debug.*" -exec cat {} \;

      - name: Gather artifacts
        if: always()
        run: |
          tests/bin/ds-artifacts-save.sh ipa --instance EXAMPLE-COM
          tests/bin/pki-artifacts-save.sh ipa
          tests/bin/ipa-artifacts-save.sh ipa
        continue-on-error: true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ipa-subca-test
          path: /tmp/artifacts
