name: KRA Clone Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  kra-clone-test:
    name: KRA clone
    needs: build
    uses: ./.github/workflows/kra-clone-test.yml

  kra-clone-hsm-test:
    name: KRA clone with HSM
    needs: build
    uses: ./.github/workflows/kra-clone-hsm-test.yml

  kra-clone-shared-ds-test:
    name: KRA clone with shared DS
    needs: build
    uses: ./.github/workflows/kra-clone-shared-ds-test.yml

  kra-clone-replicated-ds-test:
    name: KRA clone with replicated DS
    needs: build
    uses: ./.github/workflows/kra-clone-replicated-ds-test.yml
