name: Quarkus Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    uses: ./.github/workflows/wait-for-build.yml
    secrets: inherit

  quarkus-build-test:
    name: Quarkus Build
    needs: build
    uses: ./.github/workflows/quarkus-build-test.yml

  quarkus-est-basic-test:
    name: Quarkus EST Basic
    needs: build
    uses: ./.github/workflows/quarkus-est-basic-test.yml

  quarkus-ca-basic-test:
    name: Quarkus CA Basic
    needs: build
    uses: ./.github/workflows/quarkus-ca-basic-test.yml

  quarkus-acme-basic-test:
    name: Quarkus ACME Basic
    needs: build
    uses: ./.github/workflows/quarkus-acme-basic-test.yml

  quarkus-ocsp-basic-test:
    name: Quarkus OCSP Basic
    needs: build
    uses: ./.github/workflows/quarkus-ocsp-basic-test.yml

  quarkus-kra-basic-test:
    name: Quarkus KRA Basic
    needs: build
    uses: ./.github/workflows/quarkus-kra-basic-test.yml

  quarkus-tks-basic-test:
    name: Quarkus TKS Basic
    needs: build
    uses: ./.github/workflows/quarkus-tks-basic-test.yml

  quarkus-tps-basic-test:
    name: Quarkus TPS Basic
    needs: build
    uses: ./.github/workflows/quarkus-tps-basic-test.yml
